### PR TITLE
Add more info to your profile page.

### PR DESCRIPTION
**Pull request by adamransom**
Started to add a bit more to the user page. Used the suggestions from the Trello 'card' about this. Tried to keep the style similar to what was already there.

This is just the beginning though. Is this the kind of thing you were thinking of?

### CODE REVIEW

**Comment by adamransom** [comment]
I realised that I should probably add tests, but I'm more of an rspec guy and noticed there aren't many tests so far. But I will probably add them soon.

**Comment by kkuchta** [comment]
Took me long enough to look at this.  A few issues:
- The +1 tab also includes downvotes [fixed]
- Settings tab still show when viewing someone else's user page [fixed]
- Double `<hr>` when one of the tabs has more than one and less than a full page of elements [Too lazy to fix, not a big deal].

Merged; thanks for the contribution!

**Comment by adamransom** [comment]
1. Completely forgot about downvotes, sorry about that.
2. In the version I had, it seemed that if you tried to view someone else's page you simply got a CanCan "not authorized" message, so I didn't realise others could view your page.
3. Yeah, I noticed this and will look at this if there is also other work to be done on the user page :) I'll keep an eye out for any requests regarding the profiles.

Thanks for the merge again!

**Comment by kkuchta** [comment]
Re #2- yeah, if you go to http://localhost:3000/users/123/edit, you get the unauthorized page.  The issue was that the link to go to that page was present on all user/show pages.  Simple fix, though: https://github.com/kkuchta/Vimbits/commit/378e29e5699a6c1ff0529151cfebc342569d24a8  :)

**Pull request merged**
